### ISSUE TITLE
webui模块在打包编译时抛出HTMLParser解析错误,麻烦帮确认一下吗?

### ISSUE THREAD

**Issue by lymons** [kinget007/TestPlatformDemo#1]
按照Readme.md中写的顺序,依次使用下面的命令打包编译各个模块,在最后一个模块 **webui**时,抛出了错误.
`./mvnw -Pprod clean package`

打包环境
* Macbook Pro
* Mac OSX 10.12.4
* node 6.10.0
* mongoDB 3.4.4
* Java(TM) SE Runtime Environment (build 1.8.0_121-b13)

错误主要出现在:
```
[ERROR] Error: Parse Error: <</option>
[ERROR]                                                  <option value="<="><=</option>
```
我想应该是XML里面出现了`<`和`>`这样的非法字符.
我搜索了全工程,只有下面两个文件中出来这样的非法字符,但是我把如下文件中的<改成了`&lt; `, >改成了`&gt; `, 然后在编译还是出现同样的错误.
* src/main/webapp/app/maincontent/apimanage/api-manage/api-manage.html ` L235行`
* src/main/webapp/app/maincontent/apiauto/scenario/scenario-detail.controller.js `L1679行`

详细的错误如下:

```
[INFO] [16:22:57] Tested 3 tests, 3 passes, 0 failures: PASS
[ERROR] 
[ERROR] events.js:160
[ERROR]       throw er; // Unhandled 'error' event
[ERROR]       ^
[ERROR] Error: Parse Error: <</option>
[ERROR]                                                                                         <option value="<="><=</option>
[ERROR]                                                                                         <option value="Contains Key">Contains Key</option>
[ERROR]                                                                                         <option value="!Contains Key">!Contains Key</option>
[ERROR]                                                                                         <option value="Contains Value">Contains Value</option>
[ERROR]                                                                                         <option value="!Contains Value">!Contains Value</option>
[ERROR]                                                                                     </select>
[ERROR]                                                                                 </td>
[ERROR]                                                                                 <!--<td class="col-md-3"><input type="text"-->
[ERROR]                                                                                                             <!--class="form-control"-->
[ERROR]                                                                                                             <!--value="{{check.targetField}}">-->
[ERROR]                                                                                 <!--</td>-->
[ERROR]                                                                                 <td class="col-md-3"><input type="text"
[ERROR]                                                                                                             class="form-control"
[ERROR]                                                                                                             value="{{check.expectValue}}">
[ERROR]                                                                                 </td>
[ERROR]                                                                             </tr>
[ERROR]                                                                             </tbody>
[ERROR]                                                                         </table>
[ERROR]                                                                         <!--@*<div ng-jsoneditor="onLoad" ng-model="editor_code.data" options="editor_code.options" style="height: 250px;"></div>*@-->
[ERROR]                                                                     </div>
[ERROR]                                                                 </div>
[ERROR]                                                             </div>
[ERROR]                                                         </div>
[ERROR]                                                     </div>
[ERROR] 
[ERROR]                                                 </div>
[ERROR]                                             </div>
[ERROR]                                         </div>
[ERROR]                                     </div>
[ERROR]                                 </div>
[ERROR]                             </div>
[ERROR] 
[ERROR]                         </div>
[ERROR]                     </div>
[ERROR] 
[ERROR]                 </div><!-- /.box-body -->
[ERROR]             </div><!-- /.box -->
[ERROR] 
[ERROR]         </div><!-- /.col -->
[ERROR]     </div>
[ERROR] </div>
[ERROR] 
[ERROR] <div class="modal fade" id="myResult" tabindex="-1" role="dialog" aria-labelledby="myModalResult" aria-hidden="true" data-backdrop="static">
[ERROR]     <div class="modal-dialog modal-lg">
[ERROR]         <div class="modal-content">
[ERROR]             <div class="modal-header">
[ERROR]                 <button type="button" class="close" data-dismiss="modal" aria-hidden="true"
[ERROR]                         ng-click="vm.clear()">&times;</button>
[ERROR]                 <h4 class="modal-title">RESPONSE</h4>
[ERROR]             </div>
[ERROR]             <div class="modal-body">
[ERROR]                 <jhi-alert-error></jhi-alert-error>
[ERROR]                 <div class="container-fluid">
[ERROR]                     <div class="row">
[ERROR]                         <div class="col-md-12">
[ERROR]                             <div class="panel-group" id="panel_result">
[ERROR]                                 <div class="panel panel-default" ng-repeat="(orderNum,ScenarioApiInfoResult) in requestAll">
[ERROR]                                     <div class="panel-heading">
[ERROR]                                         <a class="panel-title collapsed" data-toggle="collapse" data-parent="#panel_result" href="/#/scenario-list/{{scenarioId}}#panel_result_{{orderNum}}">
[ERROR]                                             <span class="col-lg-1">{{orderNum}}</span>
[ERROR]                                             <span class="col-lg-1">{{ScenarioApiInfoResult.httpMethod}}</span>
[ERROR]                                             <span class="col-lg-9">{{ScenarioApiInfoResult.scheme}}://{{ScenarioApiInfoResult.host}}{{ScenarioApiInfoResult.basePath}}{{ScenarioApiInfoResult.pathUrl}}</span>
[ERROR]                                             <span>{{getResultFromResponse(ScenarioApiInfoResult.checks)}}</span>
[ERROR]                                         </a>
[ERROR]                                     </div>
[ERROR] 
[ERROR]                                     <div id="panel_result_{{orderNum}}" class="panel-collapse collapse">
[ERROR]                                         <div class="panel-body">
[ERROR]                                             <div class="row">
[ERROR]                                                 <div class="col-md-12">
[ERROR]                                                     <div>
[ERROR]                                                         <div ng-jsoneditor="onLoad" ng-model="ScenarioApiInfoResult.response" prefer-text="true" options="{mode:'tree'}" style="height: 250px;"></div>
[ERROR]                                                     </div>
[ERROR]                                                 </div>
[ERROR]                                                 <div class="col-md-12" ng-hide="{{ScenarioApiInfoResult.checks.length==0}}">
[ERROR]                                                     <div class="margin">
[ERROR]                                                         <table class="table table-condensed" id="myChecks_result_{{orderNum}}">
[ERROR]                                                             <tbody>
[ERROR]                                                             <tr class="btn-instagram">
[ERROR]                                                                 <th>Field Name</th>
[ERROR]                                                                 <th>Method</th>
[ERROR]                                                                 <!--<th>Target Field</th>-->
[ERROR]                                                                 <th>Expect</th>
[ERROR]                                                                 <th>Status</th>
[ERROR]                                                             </tr>
[ERROR]                                                             <tr ng-repeat="check in ScenarioApiInfoResult.checks">
[ERROR]                                                                 <td class="col-md-3">{{check.field}}</td>
[ERROR]                                                                 <td>{{check.checkMethod}}</td>
[ERROR]                                                                 <!--<td class="col-md-3"><input type="text" class="form-control" value="{{check.targetField}}"></td>-->
[ERROR]                                                                 <td class="col-md-3">{{check.expectValue}}</td>
[ERROR]                                                                 <td class="col-md-1">{{check.status}}</td>
[ERROR]                                                             </tr>
[ERROR]                                                             </tbody>
[ERROR]                                                         </table>
[ERROR]                                                         <!--@*<div ng-jsoneditor="onLoad" ng-model="editor_code.data" options="editor_code.options" style="height: 250px;"></div>*@-->
[ERROR]                                                     </div>
[ERROR] 
[ERROR]                                                 </div>
[ERROR]                                             </div>
[ERROR]                                         </div>
[ERROR]                                     </div>
[ERROR]                                 </div>
[ERROR]                             </div>
[ERROR]                         </div>
[ERROR]                     </div> <!-- /.col-md-12 -->
[ERROR]                 </div>
[ERROR]             </div>
[ERROR]             <div class="modal-footer">
[ERROR]                 <button type="button" class="btn btn-default" data-dismiss="modal" ng-click="vm.clear()">
[ERROR]                     <span class="glyphicon glyphicon-ban-circle"></span>&nbsp;<span
[ERROR]                     data-translate="entity.action.cancel">确认</span>
[ERROR]                 </button>
[ERROR]                 <!--<button type="button" ng-disabled="runForm.$invalid || vm.isSaving" class="btn btn-primary">-->
[ERROR]                     <!--<span class="glyphicon glyphicon-save"></span>&nbsp;<span></span>-->
[ERROR]                 <!--</button>-->
[ERROR]             </div>
[ERROR]         </div>
[ERROR]     </div>
[ERROR] </div>
[ERROR]     at new HTMLParser (/Users/liutao/Workspace/TestPlatform/TestPlatformDemo/webui/node_modules/html-minifier/src/htmlparser.js:235:13)
[ERROR]     at minify (/Users/liutao/Workspace/TestPlatform/TestPlatformDemo/webui/node_modules/html-minifier/src/htmlminifier.js:946:3)
[ERROR]     at Object.exports.minify (/Users/liutao/Workspace/TestPlatform/TestPlatformDemo/webui/node_modules/html-minifier/src/htmlminifier.js:1299:10)
[ERROR]     at objectAssign.fileName (/Users/liutao/Workspace/TestPlatform/TestPlatformDemo/webui/node_modules/gulp-htmlmin/index.js:22:39)
[ERROR]     at module.exports (/Users/liutao/Workspace/TestPlatform/TestPlatformDemo/webui/node_modules/tryit/tryit.js:8:9)
[ERROR]     at minifyHtml (/Users/liutao/Workspace/TestPlatform/TestPlatformDemo/webui/node_modules/gulp-htmlmin/index.js:21:9)
[ERROR]     at Transform.htmlminTransform [as _transform] (/Users/liutao/Workspace/TestPlatform/TestPlatformDemo/webui/node_modules/gulp-htmlmin/index.js:51:7)
[ERROR]     at Transform._read (/Users/liutao/Workspace/TestPlatform/TestPlatformDemo/webui/node_modules/readable-stream/lib/_stream_transform.js:159:10)
[ERROR]     at Transform._write (/Users/liutao/Workspace/TestPlatform/TestPlatformDemo/webui/node_modules/readable-stream/lib/_stream_transform.js:147:83)
[ERROR]     at doWrite (/Users/liutao/Workspace/TestPlatform/TestPlatformDemo/webui/node_modules/readable-stream/lib/_stream_writable.js:338:64)
[ERROR]     at writeOrBuffer (/Users/liutao/Workspace/TestPlatform/TestPlatformDemo/webui/node_modules/readable-stream/lib/_stream_writable.js:327:5)
[ERROR]     at Transform.Writable.write (/Users/liutao/Workspace/TestPlatform/TestPlatformDemo/webui/node_modules/readable-stream/lib/_stream_writable.js:264:11)
[ERROR]     at write (/Users/liutao/Workspace/TestPlatform/TestPlatformDemo/webui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
[ERROR]     at flow (/Users/liutao/Workspace/TestPlatform/TestPlatformDemo/webui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
[ERROR]     at DestroyableTransform.pipeOnReadable (/Users/liutao/Workspace/TestPlatform/TestPlatformDemo/webui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
[ERROR]     at emitNone (events.js:86:13)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 26.310 s
[INFO] Finished at: 2017-06-02T16:22:58+08:00
[INFO] Final Memory: 34M/361M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.2:gulp (gulp build) on project webui: Failed to run task: 'gulp.js build --no-notification' failed. (error code 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by kinget007** [comment]
修改错地方了/src/main/webapp/app/maincontent/apiauto/scenario/scenario-detail.html

**Comment by lymons** [comment]
@kinget007 thx!
